// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMMEcdc_pTjfLAbvkztWaoTI6EnC8waSg',
    appId: '1:909040654663:web:1cb2d0aa94409c5c5dd462',
    messagingSenderId: '909040654663',
    projectId: 'flash-chat-3b72e',
    authDomain: 'flash-chat-3b72e.firebaseapp.com',
    storageBucket: 'flash-chat-3b72e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoabiZxMO8KvIMspye2uyikS610_B_RwU',
    appId: '1:909040654663:android:a426f876b0cb7e485dd462',
    messagingSenderId: '909040654663',
    projectId: 'flash-chat-3b72e',
    storageBucket: 'flash-chat-3b72e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy6uYfibsBuP6bXtAF_2eIFQC-5szVhoQ',
    appId: '1:909040654663:ios:5e01ad8cb1c445495dd462',
    messagingSenderId: '909040654663',
    projectId: 'flash-chat-3b72e',
    storageBucket: 'flash-chat-3b72e.appspot.com',
    iosClientId: '909040654663-rclo24e9km9phuegmq30l1s6rfaotqeb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy6uYfibsBuP6bXtAF_2eIFQC-5szVhoQ',
    appId: '1:909040654663:ios:5e01ad8cb1c445495dd462',
    messagingSenderId: '909040654663',
    projectId: 'flash-chat-3b72e',
    storageBucket: 'flash-chat-3b72e.appspot.com',
    iosClientId: '909040654663-rclo24e9km9phuegmq30l1s6rfaotqeb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );
}
